### ISSUE TITLE
Seems solution value not captured by controller

### ISSUE THREAD

**Issue by mrprajesh** [laser-ufpb/CVRPController#17]
Hello Team,
When we ran our **deterministic** heuristic solver (it is not an iterative refinement algorithm) it prints the routes and cost. 
```
build $ ./Solver ../InstancesRounded/X-n101-k25.vrp 1
Route #1: 32 24 31 95
...
Route #30: 41 22 15 5
Cost 33181.167969

```

When we ran our solver using the controller, it seems to not capture the `Solution value, local machine time, standardized time`. Though we had done a `fflush(stdout)` after printing the cost.
```
./CVRPController Resilience ../InstancesRounded/X-n101-k25.vrp 1 2064 1800 13332 1 Solver
<snip>
Wed 08 Dec 2021 01:05:33 AM IST
timestamp: 1638905733
Solution value, local machine time, standardized time
Primal Integral: 10.0000000000
```
Will the controller only works for local search algorithms? Do you have any thoughts on this? Are we missing something? Thanks.
Kind regards,
Rajesh

**Comment by EduardoQueiroga** [comment]
Dear @mrprajesh 

Could you send the complete solution?

Thanks

**Comment by mrprajesh** [comment]
Sorry, @EduardoQueiroga. I should have written in full earlier.
`cat X-n101-k25.sol`
```
Route #1: 32 24 31 95
Route #2: 53 33
Route #3: 93 75
Route #4: 30 79 50
Route #5: 23 19 21 100
Route #6: 8 17 34 64
Route #7: 3 40 44
Route #8: 58 12
Route #9: 18 4 66
Route #10: 84 90 76 55
Route #11: 16 69 74
Route #12: 13 92 9
Route #13: 54 68 86
Route #14: 1 70 88
Route #15: 59 67
Route #16: 60 57 72 87 48 26
Route #17: 38 47 82 77
Route #18: 14 28 63 39 25
Route #19: 10 65 42
Route #20: 78 6 37
Route #21: 36 29 43 49
Route #22: 2 45 7 96 94
Route #23: 56 80
Route #24: 61 97
Route #25: 91 27
Route #26: 52 83
Route #27: 51 71 62
Route #28: 99 98 89 81 85 11 73
Route #29: 46 35 20
Route #30: 41 22 15 5
Cost 33181.167969
```

**Comment by EduardoQueiroga** [comment]
Dear @mrprajesh 

This solution is ignored because it is worst than the Base Solution of 28150.100

Best regards

**Comment by mrprajesh** [comment]
Oh, I see. Sorry about that, Got it. Thanks a lot.
