### ISSUE TITLE
Clarification on F-n135-k7

### ISSUE THREAD

**Issue by mrprajesh** [laser-ufpb/CVRPController#18]
Dear @EduardoQueiroga 
Could you clarify if coordinate distances for instance [InstancesRounded/F-n135-k7.vrp](https://github.com/laser-ufpb/CVRPController/blob/5d1658b2e1d652c248ecf5dcbd2f4540090d50f9/InstancesRounded/F-n135-k7.vrp
) should be truncated or rounded? 
The rules document [mentions](http://dimacs.rutgers.edu/files/6916/3848/0327/CVRP_Competition_Rules.pdf)  the below.

> All 129 instances from the literature listed for Phase One use EUC 2D distances (but CMT4, CMT5, tai385, and Golden9-20 instances do not follow the TSPLIB95 convention of rounding to the nearest integer).

Kindly clarify.

PS: We should update the README.md. Currently, at two places it points to the older rules document (August 26, 2020).

**Comment by EduardoQueiroga** [comment]
Dear @mrprajesh 

For this instance, the convention is to round the distance to the nearest integer (as for all the instances in the folder InstancesRounded). README.md has been updated.

Best regards

**Comment by mrprajesh** [comment]
As all the other instances in that folder had integer coordinates, I was a little puzzled about this.  Thanks a lot, @EduardoQueiroga for clarifying. 

Kind regards,
Rajesh
