### ISSUE TITLE
Typo in Loggi-n601-k42.vrp

### ISSUE THREAD

**Issue by mrprajesh** [laser-ufpb/CVRPController#19]
It looks like the below file `Loggi-n601-k42.vrp` has `NAME` field as `Loggi-n600-k42` different from the file name. 
https://github.com/laser-ufpb/CVRPController/blob/2ed0d6229b08e4a45b5f9a89447343a5985ef6cd/InstancesExplicitDistances/Loggi-n601-k42.vrp#L1

The controller creates outputs based on `NAME` field. Because of that, the files were sorted slightly differently when we populated PI values in google sheet. // A very minor thing though, just thought of sharing. 

Thanks,
Rajesh.

**Comment by EduardoQueiroga** [comment]
It was fixed. Thanks, @mrprajesh
